name: drip
description: Stream music aesthetically.

publish_to: 'none'


version: 1.2.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=3.10.0"

analyzer:
  plugins:
    - custom_lint


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  system_theme: ^2.0.0
  flutter_acrylic: ^1.0.0+2
  url_strategy: ^0.2.0
  url_launcher: ^6.0.15
  clipboard: ^0.1.3
  fluent_ui: ^4.7.7
  http: ^1.0.0
  youtube_explode_dart: ^2.0.2
  carousel_slider: ^4.2.1
  cached_network_image: ^3.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  loading_animation_widget: ^1.0.0+3
  audio_video_progress_bar: ^0.11.0
  sliding_sheet: ^0.5.2
  fluentui_system_icons: ^1.1.158
#  material_floating_search_bar: ^0.3.7
  infinite_scroll_pagination: ^4.0.0
  msix: ^3.0.1
  random_color: ^1.0.6-nullsafety
  gradient_widgets: ^0.6.0
  window_manager: ^0.3.7
  palette_generator: ^0.3.3+2
  flutter_staggered_animations: ^1.0.0
  extended_image: ^8.1.1
  hotkey_manager: ^0.1.6
  flutter_riverpod: ^2.4.5
  riverpod_annotation: ^2.3.0

  collection: ^1.16.0
  diffutil_dart: ^3.0.0
  hooks_riverpod: ^2.1.2
  shimmer: ^2.0.0
  media_kit: ^1.1.10
  media_kit_libs_audio: ^1.0.3

  drip_api:
    path: external/drip_api
#  media_kit:
#    path: external/media_kit/media_kit
#  media_kit_libs_windows_audio:
#    path: external/media_kit/media_kit_libs_windows_audio
  known_extents_list_view_builder:
    git:
      url: https://github.com/bendelonlee/known_extents_list_view_builder.git
  easy_sidemenu:
    git:
      url: https://github.com/Spsden/easy_sidemenu.git
      ref: d244151d8df1719cf0cd08c71862300eac1cdaca
  font_awesome_flutter: ^10.3.0
  easy_debounce: ^2.0.3
#  riverpod_infinite_scroll: ^1.0.9
  flutter_dotenv: ^5.1.0
  material_floating_search_bar_2: ^0.5.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dio: ^5.3.3
  dio_cache_interceptor: ^3.4.4
  dio_cache_interceptor_hive_store: ^3.2.1






dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  hive_generator: ^2.0.0
  flutter_native_splash: ^2.1.6
  build_runner: ^2.4.6
  custom_lint:
  riverpod_generator: ^2.3.5
  riverpod_lint: ^2.3.3
  freezed: ^2.4.5
  json_serializable: ^6.7.1

  

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - .env




  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


# msix_config:
#   display_name: Drip
#   publisher_display_name: SurajPratapSingh
#   identity_name: spden.app.drip
#   msix_version: 1.0.0.0
#   logo_path: D:\beep\version2\fluentUiRewrite\dripfluentnew\Drip\assets\driplogocircle.png
#   capabilities: "internetClient"
