name: drip
description: Drip Music.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  system_theme: ^2.0.0
#  bitsdojo_window: ^0.1.1+1
  flutter_acrylic: ^1.0.0+2
  url_strategy: ^0.2.0
  url_launcher: ^6.0.15
  clipboard: ^0.1.3

  provider: ^6.0.1
  fluent_ui: ^4.1.2
  http: ^0.13.4
  youtube_explode_dart: ^1.10.9+1
  carousel_slider: ^4.2.1
  cached_network_image: ^3.2.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  loading_animation_widget: ^1.0.0+3
  audio_video_progress_bar: ^0.10.0

  sliding_sheet: ^0.5.2
  fluentui_system_icons: ^1.1.158

  material_floating_search_bar: ^0.3.7
  infinite_scroll_pagination: ^3.1.0

  msix: ^3.0.1
  random_color: ^1.0.6-nullsafety
  gradient_widgets: ^0.6.0

  window_manager: ^0.2.1

  palette_generator: ^0.3.3+2
  flutter_staggered_animations: ^1.0.0
  extended_image: ^6.2.1
  hotkey_manager: ^0.1.6

  riverpod: ^2.1.1
  flutter_riverpod: ^2.1.1
  badges: ^2.0.3
  drip_api:
    path: external/drip_api
  media_kit:
    path: external/media_kit/media_kit
  collection: ^1.16.0
  diffutil_dart: ^3.0.0
  riverpod_infinite_scroll: ^1.0.9
  pull_to_refresh: ^2.0.0
  hooks_riverpod: ^2.1.2






dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1
  hive_generator: ^1.1.2
  build_runner: ^2.1.7
  flutter_native_splash: ^2.1.6
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/




  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


# msix_config:
#   display_name: Drip
#   publisher_display_name: SurajPratapSingh
#   identity_name: spden.app.drip
#   msix_version: 1.0.0.0
#   logo_path: D:\beep\version2\fluentUiRewrite\dripfluentnew\Drip\assets\driplogocircle.png
#   capabilities: "internetClient"
